ansible_ssh_user: ansible
splunk_login_user: "{{ lookup('onepassword', 'Splunk Cluster', field='username', vault='homelab') }}"
splunk_login_pass: "{{ lookup('onepassword', 'Splunk Cluster', field='password', vault='homelab') }}"
splunk_key_general: "{{ lookup('onepassword', 'Splunk Cluster', field='pass4symmkey', vault='homelab') }}"
splunk_ssl_password: "{{ lookup('onepassword', 'Splunk Cluster', field='sslpassword', vault='homelab') }}"