ansible_ssh_user: ansible
splunk_installer: https://download.splunk.com/products/splunk/releases/7.3.1/linux/splunk-7.3.1-bd63e13aa157-Linux-x86_64.tgz
splunk_login_user: "{{ lookup('onepassword', 'Splunk Cluster', field='username', vault='homelab') }}"
splunk_login_pass: "{{ lookup('onepassword', 'Splunk Cluster', field='password', vault='homelab') }}"
