nodes:
  - name: "splunk-idx"
    count: 3
    cloud_user: "ansible"
    cloud_pass: "{{ lookup('onepassword', 'Splunk Instances', field='hashed_password', vault='homelab') }}"
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "true"
    network: "vlan14-servers"
    template: "centos7-2019-06-13"
    interface: "ens160"
    ips:
      - "172.21.14.201/24"
      - "172.21.14.202/24"
      - "172.21.14.203/24"
    gateway: "172.21.14.1"
    cloud_init: "true"
    cloud_init_custom: "false"
    cloud_config_template: "centos-cloud-config.tpl"
    metadata_template: "centos-metadata.tpl"
    network_config_template: "centos-network-config.tpl"

  - name: "splunk-mn"
    count: 1
    cloud_user: "ansible"
    cloud_pass: "{{ lookup('onepassword', 'Splunk Instances', field='hashed_password', vault='homelab') }}"
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "false"
    network: "vlan14-servers"
    template: "centos7-2019-06-13"
    interface: "ens160"
    ips:
      - "172.21.14.204/24"
    gateway: "172.21.14.1"
    cloud_init: "true"
    cloud_init_custom: "false"
    cloud_config_template: "centos-cloud-config.tpl"
    metadata_template: "centos-metadata.tpl"
    network_config_template: "centos-network-config.tpl"

  - name: "splunk-sh"
    count: 1
    cloud_user: "ansible"
    cloud_pass: "{{ lookup('onepassword', 'Splunk Instances', field='hashed_password', vault='homelab') }}"
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "false"
    network: "vlan14-servers"
    template: "centos7-2019-06-13"
    interface: "ens160"
    ips:
      - "172.21.14.205/24"
    gateway: "172.21.14.1"
    cloud_init: "true"
    cloud_init_custom: "false"
    cloud_config_template: "centos-cloud-config.tpl"
    metadata_template: "centos-metadata.tpl"
    network_config_template: "centos-network-config.tpl"

  - name: "splunk-lic"
    count: 1
    cloud_user: "ansible"
    cloud_pass: "{{ lookup('onepassword', 'Splunk Instances', field='hashed_password', vault='homelab') }}"
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "false"
    network: "vlan14-servers"
    template: "centos7-2019-06-13"
    interface: "ens160"
    ips:
      - "172.21.14.206/24"
    gateway: "172.21.14.1"
    cloud_init: "true"
    cloud_init_custom: "false"
    cloud_config_template: "centos-cloud-config.tpl"
    metadata_template: "centos-metadata.tpl"
    network_config_template: "centos-network-config.tpl"

  - name: "splunk-mc"
    count: 1
    cloud_user: "ansible"
    cloud_pass: "{{ lookup('onepassword', 'Splunk Instances', field='hashed_password', vault='homelab') }}"
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "false"
    network: "vlan14-servers"
    template: "centos7-2019-06-13"
    interface: "ens160"
    ips:
      - "172.21.14.207/24"
    gateway: "172.21.14.1"
    cloud_init: "true"
    cloud_init_custom: "false"
    cloud_config_template: "centos-cloud-config.tpl"
    metadata_template: "centos-metadata.tpl"
    network_config_template: "centos-network-config.tpl"

  - name: "splunk-ds"
    count: 1
    cloud_user: "ansible"
    cloud_pass: "{{ lookup('onepassword', 'Splunk Instances', field='hashed_password', vault='homelab') }}"
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "false"
    network: "vlan14-servers"
    template: "centos7-2019-06-13"
    interface: "ens160"
    ips:
      - "172.21.14.208/24"
    gateway: "172.21.14.1"
    cloud_init: "true"
    cloud_init_custom: "false"
    cloud_config_template: "centos-cloud-config.tpl"
    metadata_template: "centos-metadata.tpl"
    network_config_template: "centos-network-config.tpl"

  - name: "worker"
    count: 3
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "true"
    network: "vlan2119-kubernetes"
    template: "rancheros-1.5.1"
    interface: "eth0"
    ips:
      - "172.21.19.21/24"
      - "172.21.19.22/24"
      - "172.21.19.23/24"
    gateway: "172.21.19.1"
    cloud_init: "true"
    cloud_init_custom: "true"
    cloud_config_template: "rancheros-cloud-config.tpl"
    cloud_config_guestinfo_path: "cloud-init.config.data"
    cloud_config_guestinfo_encoding_path: "cloud-init.data.encoding"

  - name: "controller"
    count: 3
    ssh_public_key: "{{ lookup('onepassword', 'ops-workstation-1', section='PUBLIC', field='ssh_public_key', vault='homelab') }}"
    anti_affinity_enabled: "true"
    network: "vlan2119-kubernetes"
    template: "rancheros-1.5.1"
    interface: "eth0"
    ips:
      - "172.21.19.11/24"
      - "172.21.19.12/24"
      - "172.21.19.13/24"
    gateway: "172.21.19.1"
    cloud_init: "true"
    cloud_init_custom: "true"
    cloud_config_template: "rancheros-cloud-config.tpl"
    cloud_config_guestinfo_path: "cloud-init.config.data"
    cloud_config_guestinfo_encoding_path: "cloud-init.data.encoding"

