---
- name: Prep terraform
  import_playbook: playbooks/terraform_prep.yml

- name: Build Out the Environment
  hosts: terraform
  connection: local
  gather_facts: no
  tasks:
  - block:
    - name: Populate terraform nodes file
      template:
        src: files/nodes.tf.j2
        dest: "{{ terraform_nodes_path }}"

    - name: Run terraform apply
      terraform:
        project_path: './terraform/'
        variables: "{{ terraform_variables }}"
        force_init: true
        state: present

    always:
      - name: Cleanup terraform nodes file
        file:
          path: "{{ terraform_nodes_path }}"
          state: absent

- name: Base Node Setup
  import_playbook: playbooks/base.yml

- name: Load Balancer Configuration
  import_playbook: playbooks/loadbalancer.yml

- name: Syslog Configuration
  import_playbook: playbooks/syslog.yml

- name: Splunk Configuration
  import_playbook: playbooks/splunk.yml