---
- name: Cleanup the Environment
  hosts: terraform
  connection: local
  tasks:
  - block:
    - name: Create temporary terraform variable file
      tempfile:
        state: file
        suffix: .tfvars
      register: tmp_vars

    - name: Populate temporary terraform variable file
      template:
        src: files/terraform.tfvars.j2
        dest: "{{ tmp_vars.path }}"

    - name: Populate terraform nodes file
      template:
        src: files/nodes.tf.j2
        dest: "./terraform/nodes.tf"

    - name: Run terraform destroy
      terraform:
        project_path: './terraform/'
        variables_file: "{{ tmp_vars.path }}"
        force_init: true
        state: absent

    always:
      - name: Cleanup temporary terraform variable file
        file:
          path: "{{ tmp_vars.path }}"
          state: absent
