---
- name: Cleanup the Environment
  hosts: terraform
  connection: local
  tasks:
  - name: Run terraform destroy
    terraform:
      project_path: './terraform/'
      variables: "{{ terraform_variables }}"
      force_init: true
      state: absent