---
- name: Cleanup the Environment
  hosts: terraform
  connection: local
  tasks:
  - block:
    - name: Populate terraform nodes file
      template:
        src: files/nodes.tf.j2
        dest: "{{ terraform_nodes_path }}"

    - name: Run terraform destroy
      terraform:
        project_path: './terraform/'
        variables: "{{ terraform_variables }}"
        force_init: true
        state: absent

    always:
      - name: Cleanup terraform nodes file
        file:
          path: "{{ terraform_nodes_path }}"
          state: absent
