---
- name: chrisbalmer.cloud-growpart
  scm: git
  src: git+https://github.com/chrisbalmer/ansible-role-cloud-growpart.git
  version: 0.1.1
- name: chrisbalmer.splunk-installation
  scm: git
  src: git+https://github.com/chrisbalmer/ansible-role-splunk-installation.git
  version: 0.1.5