- name: Docker Deployment
  hosts: docker
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Test OP timeout
      command: op list users
      run_once: true
      delegate_to: localhost
      become: no
  roles:
    - geerlingguy.nfs
    - geerlingguy.docker
    - geerlingguy.pip