- name: Load Balancer Deployment
  hosts: loadbalancer
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Test OP timeout
      command: op list users
      run_once: true
      delegate_to: localhost
      become: no
