- name: Splunk Deployment
  hosts: splunk
  become: yes
  gather_facts: no
  tasks:
    - setup:
    # - name: Download Splunk
    #   get_url:
    #     url: "{{ splunk_linux_build_url }}"
    #     dest: "/tmp/{{ splunk_linux_filename }}"
